# Information
title: Max Blog
email: max-lorenz@gmx.net
baseurl: ""
repository: "maxlorenz/maxlorenz.github.io"
url: ""
github_username: maxlorenz

# Build settings
theme: jekyll-theme-minimal
highlighter: rouge

# Plugins
plugins:
  - jekyll-org
